Add support for NUnit format
jenkinsci/coverage-model pull request #69
Opened 2024-01-23 14:34 UTC by jonesbusy

Add test count metric for NUnit which is a famous test runner for .NET project (Similar to JUnit).

The XML format is somehow similar but different (different tag, attributes, or errors message stored deeper on the XML structure

It's possible there is duplicate between the JUnit and NUnit parser. We could perhaps move some utils to the parent class

### Testing done

- 100% test coverage

![coverage_nunit](https://github.com/jenkinsci/coverage-model/assets/825750/8e711751-4227-48eb-8413-4006bb880cce)

- Support of NUnit 2 and NUnit 3 format (https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html)

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-01-23 16:17 UTC, uhafner requested changes
Thanks for adding this parser. I'm not sure if you can use it in the same way I am using it with JaCoCo and JUnit. The mapping of tests to SUT classes is currently done by looking at the package and class names. This does not work for reports without packages.

2024-01-23 16:17 UTC, uhafner commented on src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java
> + * Parses reports in the NUnit format (https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html) into a Java object model.
```suggestion
 * Parses reports in the <a href="https://docs.nunit.org/articles/nunit/technical-notes/usage/Test-Result-XML-Format.html">NUnit format</a> into a Java object model.
```

2024-01-23 16:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/coverage/parser/NunitParser.java
> +            builder.withStatus(TestCase.TestResult.SKIPPED);
The default should not appear twice.

2024-01-23 16:30 UTC, uhafner commented
I think that I will extract the duplicate code after the merge into a new base class.

2024-01-24 05:14 UTC, jonesbusy commented
> Thanks for adding this parser. I'm not sure if you can use it in the same way I am using it with JaCoCo and JUnit. The mapping of tests to SUT classes is currently done by looking at the package and class names. This does not work for reports without packages.

Good point but for NUnit / OpenCover I don't think I can do anything

It's a common pattern for .NET to store the tests to a test module (not like java where 'test' folder is part of the same module) and generally test are part of the same package for package access

I can extract the `fullname` attribute of the test-case (example fullname=`"test.Tests.IgnoredTest"`) but I cannot map it to anything.

The 'test' module will not even exist on OpenCover side

2024-01-24 05:14 UTC, jonesbusy commented
The other points are fixed now and all checks are green now

2024-01-24 06:38 UTC, jonesbusy commented
Created a draft PR to include the parser into the plugin : https://github.com/jenkinsci/coverage-plugin/pull/66

Will be finalized when release (now it's pointing to incrementals of this PR)

2024-01-24 07:28 UTC, uhafner approved these changes

2024-01-24 07:35 UTC, uhafner commented
> > Thanks for adding this parser. I'm not sure if you can use it in the same way I am using it with JaCoCo and JUnit. The mapping of tests to SUT classes is currently done by looking at the package and class names. This does not work for reports without packages.
> 
> Good point but for NUnit / OpenCover I don't think I can do anything
> 
> It's a common pattern for .NET to store the tests to a test module (not like java where 'test' folder is part of the same module) and generally test are part of the same package for package access
> 
> I can extract the `fullname` attribute of the test-case (example fullname=`"test.Tests.IgnoredTest"`) but I cannot map it to anything.
> 
> The 'test' module will not even exist on OpenCover side

I see. In Java the mapping of test case to SUT is also done using a heuristic that might fail if developers do not respect the conventions.

2024-01-24 07:35 UTC, merged